/**
 * Scans the source tree for Iconify icon names ("prefix:name") and writes a
 * trimmed offline bundle to lib/icon-bundle.ts.
 *
 * Keeping the bundle local means icons render during SSR with no request to
 * api.iconify.design and no pop-in after hydration. Re-run after adding a new
 * icon: `bun run icons` (also wired into `prebuild`).
 */
import { createRequire } from "node:module"
import { readdir, readFile, writeFile } from "node:fs/promises"
import { extname, join, relative } from "node:path"
import { fileURLToPath } from "node:url"
import { getIcons, minifyIconSet } from "@iconify/utils"

const require = createRequire(import.meta.url)
const ROOT = fileURLToPath(new URL("..", import.meta.url))

/** Collections we allow icons from, in `@iconify-json/<pkg>` form. */
const COLLECTIONS = ["lucide", "simple-icons", "devicon-plain"]

const SCAN_DIRS = ["app", "components", "lib"]
const SCAN_EXTS = new Set([".ts", ".tsx", ".js", ".jsx", ".mdx"])
const SKIP_DIRS = new Set(["node_modules", ".next", ".git", "dist"])

const OUT_FILE = join(ROOT, "lib/icon-bundle.ts")

// Matches a quoted "prefix:name" literal, e.g. "lucide:arrow-right".
const ICON_RE = new RegExp(
  `["'\`](${COLLECTIONS.join("|")}):([a-z0-9][a-z0-9-]*)["'\`]`,
  "g"
)

async function* walk(dir) {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    if (entry.name.startsWith(".") || SKIP_DIRS.has(entry.name)) continue
    const full = join(dir, entry.name)
    if (entry.isDirectory()) yield* walk(full)
    else if (SCAN_EXTS.has(extname(entry.name))) yield full
  }
}

/** @returns {Map<string, Map<string, string[]>>} prefix -> name -> source files */
async function collectUsedIcons() {
  const used = new Map(COLLECTIONS.map((prefix) => [prefix, new Map()]))

  for (const dir of SCAN_DIRS) {
    for await (const file of walk(join(ROOT, dir))) {
      const source = await readFile(file, "utf8")
      for (const [, prefix, name] of source.matchAll(ICON_RE)) {
        const byName = used.get(prefix)
        const sources = byName.get(name) ?? []
        sources.push(relative(ROOT, file))
        byName.set(name, sources)
      }
    }
  }

  return used
}

function loadCollection(prefix) {
  const path = require.resolve(`@iconify-json/${prefix}/icons.json`)
  return readFile(path, "utf8").then(JSON.parse)
}

async function main() {
  const used = await collectUsedIcons()
  const bundles = []
  const problems = []
  let total = 0

  for (const prefix of COLLECTIONS) {
    const names = [...used.get(prefix).keys()].sort()
    if (names.length === 0) continue

    const iconSet = await loadCollection(prefix)
    const subset = getIcons(iconSet, names)
    const found = subset ? Object.keys(subset.icons).length : 0

    if (!subset || found < names.length) {
      const resolved = new Set([
        ...Object.keys(subset?.icons ?? {}),
        ...Object.keys(subset?.aliases ?? {}),
      ])
      for (const name of names) {
        if (resolved.has(name)) continue
        problems.push(
          `  ${prefix}:${name} — not in @iconify-json/${prefix} ` +
            `(used in ${used.get(prefix).get(name).join(", ")})`
        )
      }
    }

    if (subset) {
      minifyIconSet(subset)
      bundles.push(subset)
      total += found
    }
  }

  if (problems.length > 0) {
    console.error("Unknown icon names:\n" + problems.join("\n"))
    process.exit(1)
  }

  const body = bundles
    .map((set) => `addCollection(${JSON.stringify(set)})`)
    .join("\n\n")

  await writeFile(
    OUT_FILE,
    [
      "// Generated by scripts/build-icons.mjs — do not edit by hand.",
      "// Run `bun run icons` after adding or removing an icon.",
      'import { addCollection } from "@iconify/react/offline"',
      "",
      body,
      "",
    ].join("\n")
  )

  console.log(
    `icons: bundled ${total} icons from ${bundles.length} collection(s) -> ` +
      relative(ROOT, OUT_FILE)
  )
}

await main()
